version: "3"
services:
    neo4j:
        image: neo4j:4.0.3
#        build:
#            context: .
#            dockerfile: Dockerfile.neo4j.dev
        container_name: neo4j-db
        restart: unless-stopped
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./neo4j/conf:/conf
            - ./neo4j/data:/data
            - ./ETL/processedData/mysqlData/:/import
            - ./neo4j/logs:/logs
            - ./neo4j/plugins:/plugins
            - ./ETL/load/neo4jLoad:/import/load
        environment:
            # Raise memory limits
            - NEO4J_dbms_memory_pagecache_size=2G
            - NEO4J_dbms.memory.heap.initial_size=4G
            - NEO4J_dbms_memory_heap_max__size=8G
            - NEO4J_AUTH=neo4j/your_password
            - dbms.connector.bolt.listen_address=bolt://neo4j:pass@neo4j_db:7687
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
#            - NEO4JLABS_PLUGINS=["apoc"]
    db:
        image: mysql:8
        container_name: mysql-db
        restart: unless-stopped
        ports:
            - 13306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/config:/etc/mysql/conf.d
            - ./ETL/load/mysqlLoad:/script
            - ./ETL/processedData/mysqlData/:/dw_data/mysqlData/
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: your_password
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --secure-file-priv=''

